sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker
install:
  - cd src/main/gui/ && npm install && bower install
  - grunt build --force
  - cd ../../../
  - mvn -DskipTests install
  #- mvn install -Dmaven.javadoc.skip=true -B -V

before_install:
  - sudo apt-get update && sudo apt-get install -y nodejs npm
  - npm install -g grunt grunt-cli bower
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_success:
  - docker build -t fgiana/yporque:latest .
  - docker run --name yporque -d -P fgiana/yporque:latest
  - docker ps
  - docker port yporque
  - docker push fgiana/yporque:latest
