package yporque.model;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.*;

/**
 * Created by francisco on 21/11/15.
 */
@Entity
@Table(name="item")
public class Item {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="item_id", nullable = false)
    private Long itemId;
    @Column(name="articulo_id")
    private Long articuloId;
    private String codigo;
    private Integer cantidad;

    @ManyToOne()
    @JoinColumn(name="articulo_id",referencedColumnName="articulo_id", insertable = false, updatable = false)
    private Articulo articulo;

    public Articulo getArticulo() {
        return articulo;
    }

    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }

    public Item() {
    }

    public Item(String codigo, Integer cantidad) {
        this.codigo = codigo;
        this.cantidad = cantidad;
    }

    public Long getArticuloId() {
        return articuloId;
    }

    public void setArticuloId(Long articuloId) {
        this.articuloId = articuloId;
    }

    public Long getItemId() {
        return itemId;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Integer getCantidad() {
        return cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
}
